### ISSUE TITLE
DateTime Picker is not taking up full space

### ISSUE THREAD

**Issue by ice-rahul** [dohomi/tamagui-kitchen-sink#26]
DateTime Picker when used, does not have any option to set it to full width

Because of this it appears buggy and contains lots of space toward the right

This should be an option for the entire width (fullWidth) as we have for input fields

Attaching video for reference

https://github.com/dohomi/tamagui-kitchen-sink/assets/22559660/cb2aaf9d-f09a-46e2-bc0b-4220c79862b7

**Comment by dohomi** [comment]
@ice-rahul on mobile the date picker component should look entirely different as I use a different component for native:
https://github.com/dohomi/tamagui-kitchen-sink/blob/master/packages/date/src/datepicker/LmDatepicker.native.tsx#L1

But thanks your video is clear I will have to check how to position in case of a web browser use of small device a better flexbox alignment

**Comment by dohomi** [comment]
Fixed in the newest release

**Comment by Carbowix** [comment]
I noticed also when you use, the date range picker on mobile devices. Only one calendar will show and the other one will be in the overflow view. Like that: 
![image](https://github.com/dohomi/tamagui-kitchen-sink/assets/24420693/1f5bec9a-8961-4802-a34c-52bc2bc37493)

That's the view of the sheet when you try to use it on a bigger screen which clearly shows that both date pickers are kinda forced to show beside each other.
![image](https://github.com/dohomi/tamagui-kitchen-sink/assets/24420693/5952257f-f208-4565-8aa1-7bdb07b8da73)

Would be nice also if I can have full control of the sheet in order to set the snap points, show the handle, etc.

**Comment by dohomi** [comment]
Will have a look, I actually thought that I set the number of months via https://github.com/dohomi/tamagui-kitchen-sink/blob/master/packages/date/src/datepicker/LmDatepicker.tsx#L44

I will revisit this again. For sure forwarding all Popover props will not be difficult I will work on this soon.

**Comment by dohomi** [comment]
New version is released, now you can pass `popoverProps` to the underlying popover. Let me know if this fixes your requirement.

**Comment by Carbowix** [comment]
@dohomi thank you it works better now, Only issue I think is that it's not centered on larger resolution mobile devices:
![image](https://github.com/dohomi/tamagui-kitchen-sink/assets/24420693/d6573479-c311-4041-9445-115c0f90608f)

Also a silly question, I've been getting an error because you are using a native date picker. I'm using a similar setup to your repo., and I have `@tamagui-extras/date` installed in [`packages/ui`](https://github.com/chen-rn/CUA/tree/main/packages/ui) which is a folder containing all my tamagui components and packages, so in theory, it should work perfectly. Is there a react-native specific package I need to install in my `apps/expo` directory in order to prevent that error?
![image](https://github.com/dohomi/tamagui-kitchen-sink/assets/24420693/1d26d60b-1d6c-44a7-ab0f-d4f52f25b635)

**Comment by dohomi** [comment]
> @dohomi thank you it works better now, Only issue I think is that it's not centered on larger resolution mobile devices: ![image](https://user-images.githubusercontent.com/24420693/240882565-d6573479-c311-4041-9445-115c0f90608f.png)
> 
> Also a silly question, I've been getting an error because you are using a native date picker. I'm using a similar setup to your repo., and I have `@tamagui-extras/date` installed in [`packages/ui`](https://github.com/chen-rn/CUA/tree/main/packages/ui) which is a folder containing all my tamagui components and packages, so in theory, it should work perfectly. Is there a react-native specific package I need to install in my `apps/expo` directory in order to prevent that error? ![image](https://user-images.githubusercontent.com/24420693/240884471-1d26d60b-1d6c-44a7-ab0f-d4f52f25b635.png)

your image how do you get into this stage? I mostly only see either Popup or the native picker?

About the native issue, can you have a look if you are using similar setup for babel.config.js, maybe also the metro.config.js, check out the /apps/expo app.

https://github.com/dohomi/tamagui-kitchen-sink/blob/master/apps/expo/babel.config.js

That runs at least in Expo Go
<img width="411" alt="Screenshot 2023-05-26 at 13 12 16" src="https://github.com/dohomi/tamagui-kitchen-sink/assets/489221/928910c6-0a3b-4d4b-b64a-795cf77284e4">

**Comment by Carbowix** [comment]
About the date-picker image, you can simply check it in the browser.

For the RNDatePicker error, ~~I couldn't find a proper fix for the issue since it happens on Android. I'll probably try my luck with another package and see if it works.~~ I noticed that my expo version is a little outdated for the date-time-picker, and updating it made more issues. So I decided to patch the `tamagui-extras/date` to downgrade the date-time-picker to the version that is compatible with my expo SDK which made it work fine. I guess I'll have to live with it until I find out how to fix the issues when updating the expo.

**Comment by tjapa** [comment]
> About the date-picker image, you can simply check it in the browser.
> 
> For the RNDatePicker error, ~I couldn't find a proper fix for the issue since it happens on Android. I'll probably try my luck with another package and see if it works.~ I noticed that my expo version is a little outdated for the date-time-picker, and updating it made more issues. So I decided to patch the `tamagui-extras/date` to downgrade the date-time-picker to the version that is compatible with my expo SDK which made it work fine. I guess I'll have to live with it until I find out how to fix the issues when updating the expo.

How you did this?

**Comment by tjapa** [comment]
> About the date-picker image, you can simply check it in the browser.
> 
> For the RNDatePicker error, ~I couldn't find a proper fix for the issue since it happens on Android. I'll probably try my luck with another package and see if it works.~ I noticed that my expo version is a little outdated for the date-time-picker, and updating it made more issues. So I decided to patch the `tamagui-extras/date` to downgrade the date-time-picker to the version that is compatible with my expo SDK which made it work fine. I guess I'll have to live with it until I find out how to fix the issues when updating the expo.

How you did this, @Carbowix?

The same problem happens to me, @dohomi .

**Comment by dohomi** [comment]
@tjapa as mentioned above it seems that the Expo version mismatch was the reason for the RN picker not to work. Can you compare your version with the /apps/expo version of this kitchen sink?

**Comment by tjapa** [comment]
@dohomi seens to be a problem with @react-native-community/datetimepicker > 7.0.0 and Expo.
I added ```"@react-native-community/datetimepicker": "6.7.5"``` to ```resolutions``` in the ```package.json``` and it's working!

**Comment by dohomi** [comment]
I'll close this issue for now

**Comment by pmould** [comment]
<img width="339" alt="Screenshot 2023-11-21 at 5 07 11 AM" src="https://github.com/dohomi/tamagui-kitchen-sink/assets/5210234/37e89283-2b72-4bf8-af86-39f7458b2588">

I'm getting this error:
`"RNDateTimePicker" cannot be found in UIManager`


@dohomi My babel.config.js and metro.config.js is the same as in this repo.

I am using pnpm package manager and added the resolution to downgrade the package and verified in my node_modules using this configuration as mentioned here https://github.com/dohomi/tamagui-kitchen-sink/issues/26#issuecomment-1569368128:

```
  "pnpm": {
    "overrides": {
      "@react-native-community/datetimepicker": "6.7.0"
    }
  },
```
